In [2]:
%load_ext autoreload
%autoreload 2

import matplotlib
from matplotlib import pyplot
pyplot.ion()
pyplot.style.use('dark_background')

import torch as th
from rl.algs.dqn import *

In [3]:
# GridWorld (debugging)
from rl.algs import experiment
from rl.algs import model
from rl.algs.envs import grid_world

BATCH_SIZE = 32
TRAIN_START_STEP = 3 * BATCH_SIZE
NUM_TRAIN_STEPS = 10000 # 17
REPLAY_SIZE = 100000
TARGET_NETWORK_UPDATE_FREQ = 500


env = environment.GridWorldWrapped(grid_shape=(4, 4, 1))
conv_specs = {
  model.ConvSpec(4, 1, 32),
}
fc_specs = (64,)
model_params = {
  'conv_specs': conv_specs,
  'fc_specs': fc_specs,
}

EPS_DECAY = util.Schedule((0, TRAIN_START_STEP, NUM_TRAIN_STEPS / 1, NUM_TRAIN_STEPS),
                          (1, 1, 0.0, 0.0))
EPS_RANDOM = util.Schedule((0,), (1.0,))
adam_params = {
  'fn': th.optim.Adam,
  'kwargs': {
    'lr': 0.005,
  }
}
rmsprop_params = {
  'fn': th.optim.RMSprop,
  'kwargs': {
    'lr': 0.00025,
    'momentum': 0.95,
    'alpha': 0.95,
    'eps': 0.01,
  }
}

policy_params = {
    'opt_params': rmsprop_params,
    'eps_sched': EPS_DECAY,  # TODO: change
    'target_update_freq': TARGET_NETWORK_UPDATE_FREQ,
}
exp = experiment.Experiment(env, model.QNetwork, model_params,
                            Dqn, policy_params)

print(exp.policy.model)

rb = ReplayBuffer(REPLAY_SIZE)
for step in range(TRAIN_START_STEP):
  sars = env.step(exp.policy.get_action)
  rb.add(sars)

eps_rew = 0
for step in range(TRAIN_START_STEP, NUM_TRAIN_STEPS):
  sars = env.step(exp.policy.get_action)
  rb.add(sars)
    
  experience_batch = rb.sample(BATCH_SIZE)
  m = exp.policy.update(experience_batch)
  
  eps_rew += sars.r
  if sars.s1 is None:
    m['r_per_eps'] = eps_rew
    eps_rew = 0
  if step % 100 == 0 or sars.s1 is None:
    for k, v in m.items():
      exp.plt.add_data(k, step, v)
      
# Expect about r_per_eps=-50 in pure random agent.

(1, 1, 32)
QNetwork(
  (convs): Sequential(
    (0): Conv2d(1, 32, kernel_size=(4, 4), stride=(1, 1))
    (1): ReLU()
  )
  (fc): Sequential(
    (0): Linear(in_features=32, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=4, bias=True)
  )
)


In [4]:
opt = grid_world.GridWorld((4, 4)).optimal_expected_reward()
print(f'optimal expected r: {opt}')

optimal expected r: 1.6666666666666665


In [5]:
env.show_model_policy(exp.policy.model)

[[ 0.         -1.10237765 -2.74043155 -3.70986867]
 [-0.02331477 -1.02059114 -1.93267167 -2.89601326]
 [-1.05153155 -2.0443778  -2.86948395 -3.62305117]
 [-2.11386776 -3.02460194 -3.69501328 -4.47181273]]
[['⟲' '←' '←' '↓']
 ['↑' '←' '←' '←']
 ['↑' '↑' '↑' '←']
 ['↑' '↑' '←' '←']]
[[-0.02633896  0.          0.01066093 -0.86178029]
 [-1.09013367 -0.17533314 -1.03090715 -1.87787163]
 [-2.03442526 -1.11998558 -1.96745574 -2.72577691]
 [-3.10714889 -2.24978161 -3.05880117 -3.58289409]]
[['→' '⟲' '←' '←']
 ['→' '↑' '←' '←']
 ['→' '↑' '↑' '←']
 ['→' '↑' '←' '←']]
[[-1.15293825e+00 -1.69909000e-03  0.00000000e+00 -3.22088122e-01]
 [-1.78301764e+00 -9.98633206e-01 -9.85495448e-02 -1.20000935e+00]
 [-2.68299413e+00 -1.75351644e+00 -1.05165184e+00 -1.83264196e+00]
 [-3.66128588e+00 -2.65871739e+00 -1.81867301e+00 -2.91922426e+00]]
[['→' '→' '⟲' '←']
 ['→' '→' '↑' '←']
 ['→' '→' '↑' '←']
 ['→' '→' '↑' '←']]
[[-2.14585233 -1.13854909  0.07372069  0.        ]
 [-2.92501688 -2.08488464 -1.05167449  

In [9]:
# Debug the action-value function for a given state.
s = [[0, 0, 0, 0],
     [0, 0, 0, 0],
     [0, 0, 1, 0],
     [0, 0, 2, 0]]
s = np.expand_dims(np.expand_dims(s, 0), -1)
print(exp.policy.model(util.to_variable(s)))
print(exp.policy.target_model(util.to_variable(s)))

Variable containing:
-1.8820 -1.8912 -0.0071 -1.8693
[torch.cuda.FloatTensor of size 1x4 (GPU 0)]

Variable containing:
-1.7349 -1.9211 -0.0394 -1.7967
[torch.cuda.FloatTensor of size 1x4 (GPU 0)]



In [10]:
# Examine the replay buffer.
terminals = rb.filter_by(sars_filter(r=0))
print(len(terminals))

# action-value at 's' was wrong. Search the replay buffer for occurrences of
# the correct transition. It's likely missing, which led the NN to overfit
# on missing data.
trans_s = rb.filter_by(sars_filter(s=s))
trans_s_a = rb.filter_by(sars_filter(s=s,a=2))
print(f'Num with (s): {len(trans_s)}. Num with (s, a): {len(trans_s_a)}')


1643
Num with (s): 74. Num with (s, a): 51


In [35]:
env.visualize(exp.policy, steps=20)

array([[0, 0],
       [1, 0]])
array([[0, 0],
       [1, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
array([[1, 0],
       [0, 0]])
