In [1]:
# @title Set up magic commands
%load_ext autoreload
%autoreload 2
%matplotlib inline


In [107]:
import torch
import gym
import numpy as np

import render

RENDER_RGB = 'rgb_array'
RENDER_HUMAN = 'human'

RENDER_MODE = {
  'CartPole-v0': RENDER_RGB,
  'FrozenLake-v0': RENDER_HUMAN,
}

ENV = 'FrozenLake-v0'

def examine_env():
  env = gym.make(ENV)
examine_env()

[2017-09-10 01:07:03,702] Making new env: FrozenLake-v0


In [119]:
import value_iter_agent as agent


def run_episode():
  env = gym.make(ENV)
  observation = env.reset()
  frames = [env.render(mode=RENDER_MODE[ENV])]
  
  ag = agent.ValueIterAgent((4, 4), 4)
  
  action = env.action_space.sample()
  
  for i in range(10000):
    obs, reward, done, info = env.step(action)
    action = ag.act(obs, reward, done)
    if reward:
      print(i, reward)
      print(ag._value)
      #print(ag._policy)
      print(np.argmax(ag._policy, axis=-1))

    #frames.append(env.render(mode=RENDER_MODE[ENV]))
    #print(obs, reward, info)
    if done:
      env.reset()
  env.render(close=True)
  
  print(ag._env_tx[0, 2, 0])
  if RENDER_MODE[ENV] == RENDER_RGB:
    render.display_frames_as_gif(frames)
run_episode()

[2017-09-10 01:41:42,995] Making new env: FrozenLake-v0



SFFF
FHFH
FFFH
HFFG
590 1.0
[[ 0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.0625]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
2234 1.0
[[  1.59452055e-09   1.25971990e-08   1.42230869e-07   7.94504207e-07]
 [  9.48037530e-09   5.01925192e-08   1.20177228e-06   1.27604910e-05]
 [  1.06603383e-07   2.32052508e-06   3.15283507e-05   8.92071562e-04]
 [  2.81304627e-07   1.92897730e-05   7.67770023e-04   6.42746705e-02]]
[[0 1 0 0]
 [0 0 0 0]
 [1 1 0 0]
 [1 1 1 0]]
2492 1.0
[[  2.08537376e-09   1.57780084e-08   1.75687625e-07   8.94263303e-07]
 [  1.17865640e-08   6.09070621e-08   1.38066925e-06   1.31334289e-05]
 [  1.36372534e-07   3.49771739e-06   3.98994722e-05   9.17905874e-04]
 [  2.81123911e-07   2.70395773e-05   7.87765179e-04   6.43394372e-02]]
[[1 1 0 0]
 [0 0 0 0]
 [1 1 1 0]
 [1 1 1 0]]
2732 1.0
[[  2.77370587e-09   1.78465403e-08   1.90320596e-07   8.47214382e-07]
 [  1.73176159e-08   7.1525

In [50]:
import value_iter_agent as agent

ag = agent.ValueIterAgent((4, 4), 4)
for i in range(10):
  ag.act(3, 10)
  print(ag._value)

(3, 0, 0)
(3, 1, 1)
(2, 0, 2)
(3, 0, 3)
[[  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [ 10.   0.   0.   0.]]
(3, 0, 0)
(3, 1, 1)
(2, 0, 2)
(3, 0, 3)
[[  0.    0.    0.    0. ]
 [  0.    0.    0.    0. ]
 [  0.    0.    0.    0. ]
 [ 14.5   0.    0.    0. ]]
(3, 0, 0)
(3, 1, 1)
(2, 0, 2)
(3, 0, 3)
[[  0.      0.      0.      0.   ]
 [  0.      0.      0.      0.   ]
 [  0.      0.      0.      0.   ]
 [ 16.525   0.      0.      0.   ]]
(3, 0, 0)
(3, 1, 1)
(2, 0, 2)
(3, 0, 3)
[[  0.        0.        0.        0.     ]
 [  0.        0.        0.        0.     ]
 [  0.        0.        0.        0.     ]
 [ 17.43625   0.        0.        0.     ]]
(3, 0, 0)
(3, 1, 1)
(2, 0, 2)
(3, 0, 3)
[[  0.          0.          0.          0.       ]
 [  0.          0.          0.          0.       ]
 [  0.          0.          0.          0.       ]
 [ 17.8463125   0.          0.          0.       ]]
(3, 0, 0)
(3, 1, 1)
(2, 0, 2)
(3, 0, 3)
[[  0.           0.           0.       